### ISSUE TITLE
no reference to "__sync_bool_compare_and_swap_16" on the arm64 platform

### ISSUE THREAD

**Issue by GitSoftwareNow** [AndreRH/wine#1]
when I build this project the gcc reports that no reference to "__sync_bool_compare_and_swap_16" to compilehangover/dlls/ntdll/rtl.c ,what should I do ? the gcc version is 5.4.0 junper

**Comment by stefand** [comment]
Use clang or upgrade to gcc 10. If your gcc is this old your clang is probably outdated too.

**Comment by stefand** [comment]
https://github.com/AndreRH/hangover/issues/72
