### ISSUE TITLE
shell32.dll Icon sequence

### ISSUE THREAD

**Issue by blackcrack** [AndreRH/wine#6]
Hi, 

could you check the sequence of the shell32.dll,
because it is not fit not to with Windows 2000 up to win11

it's by comparson with Wine and the MS-Winversions really confused

take a look :

win2000
![shell32-Sindows2000](https://github.com/AndreRH/wine/assets/7925717/436fe50d-f3a0-464a-8432-bb6510a44d72)

winxp
![shell32-windowsXP](https://github.com/AndreRH/wine/assets/7925717/a7a9ea5a-5bea-457b-b16f-ec76eb76cc6c)

win7
![shell32-windows7](https://github.com/AndreRH/wine/assets/7925717/c0d2e06f-32fc-4132-b352-0cc9c9ba25a4)

win10
![shell32-Windows10](https://github.com/AndreRH/wine/assets/7925717/59c139b5-781b-4452-9915-3cfca1eaa114)

win11
![shell32-Windows11](https://github.com/AndreRH/wine/assets/7925717/fdb63366-50e9-4b09-84d4-8ee52345e6ea)

**Comment by stefand** [comment]
Please file wine bugs at bugs.winehq.org. This github fork is a mostly a personal work tree, you won't find much attention here.

**Comment by blackcrack** [comment]
@stefand 
Hi Stefan, 
ich geh mal davon aus, daß Du n deutscher bisch \*g* 
bei WineBugs hab ich schon gemacht, aber man hat mich getrollt, schau's dir mal an ;
https://bugs.winehq.org/show_bug.cgi?id=54438

weil, wenn die WinNT shell32.dll reihenfolge nicht eingehalten wird, stößt es definitiv ab, zu wine zu wechseln, weil die Icons nicht passen zu angepassten Programmen und so weiter, Du bist Entwickler, der hier zugriff hat, somit ranghöher.. ich bin seit Mandrake dabei und hab damals mit Gael Corronsondiert oder wie das heist, damals als er draktools/drakconf aufbaute .. hab also die ganzen Stationen von wine mitbekommen, daher weis ich wo ich die richtigen kontaktier, a.example here \*g*
Daher versuchs ich auf den weg die richtigen an zu sprechen, weil anscheinend  bei wine recht viel konfused geht und man eben nichtmehr alles überblicken kann, daher.. hab ich mal hier aufgeschlagen...

also, könntest Du mal nach den Shell32.dll icon reihenfolge schauen ? und wenn zusätzliche icons mit eingebaut werden bei wine, dann bitte am Ende, damit die Reihenfolge nicht vermischt wird.. früher hat's gepasst, hat sich aber anscheinend die letzten Jahre geändert weil da..hmm.. will jetzt nix mutmaßen.. kannst Dir deinen eigenen teil denken.. ich sag mal aus Dummheit oder eben mit wissen und wollen, damit wine eben uninterresanter wird und nicht "fit/passt" und somit auch uninterresant wird, daher isses eben wichtig, standartsachen ein zu halten und drauf zu schauen...
Ich hab meine Totalcommander Bar auch auf die shell32 eingestellt von Win2000 bis 11 bez, derzeit verwende ich Win7 und eben Wine in Fedora .. hab das auch schon, wie de siehst mit Virtualbox überprüft..

nuja.. wie gesagt : https://bugs.winehq.org/show_bug.cgi?id=54438

könntest Du da mit den Richtigen Sprechen, Du bist da mit dabei... und bist sicher interresiert, daß
eben wine in richtiger Weise aufgebaut ist und nicht abstossend ..

Danke Dir und liebe Grüße
Blacky

blackysgate (de/net)
